Update en.yml
ualbertalib/discovery pull request #2166
Opened 2021-03-19 19:11 UTC by nnunn

Modifying bpsc_read_on_site_requests message as per Linda Quirk's helpdesk ticket https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=60275.

## Context

Minor text change to remove the need to continually update the message.

https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=60275

## What's New

Removed mention of Fall 2020 term

- [ ] `rake spec` tests pass

Remember to request a reviewer when you submit!

2021-03-19 19:54 UTC, pgwillia requested changes
Looks good.  Just need to add a [Changelog entry](https://github.com/ualbertalib/discovery/blob/bpsc-text-update/CHANGELOG.md)

2021-03-23 18:39 UTC, pgwillia commented on CHANGELOG.md
> +2021-03-19
Do you want to cut a release right away?

Then you could do:
```suggestion
## [3.5.9] - 2021-03-19
```
And update https://github.com/ualbertalib/discovery/blob/d7acb7c92dba33ed19a291440e15c3a43496a2e3/config/application.rb#L11 with 3.5.9 too.

2021-03-29 15:09 UTC, nnunn commented on CHANGELOG.md
> +2021-03-19
I don't need to cut a release - or do I? I'm fine with this change just being part of the next release as it is so small.

2021-03-30 17:08 UTC, pgwillia commented on CHANGELOG.md
> +2021-03-19
No you don't need to cut a release.  If that's not your intention this line doesn't really need to be there at all.

2021-03-31 18:20 UTC, nnunn commented on CHANGELOG.md
> +2021-03-19
Is is right now? sorry - I'm pretty rusty at this :)!

2021-04-06 15:29 UTC, merged